### ISSUE TITLE
No command in pushed image

### ISSUE THREAD

**Issue by hsiliev** [concourse/oci-build-task#118]
### Describe the bug

I'm building and publishing an image as described in:
* https://concourse-ci.org/building-and-pushing-an-image.html#build-the-image
* https://concourse-ci.org/building-and-pushing-an-image.html#publish-the-container-image

The resulting image has empty Config entries:
```
> docker inspect europe-west3-docker.pkg.dev/project/backend | jq .[0].Config
{
  "Hostname": "",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
  "AttachStdout": false,
  "AttachStderr": false,
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": null,
  "Cmd": null,
  "Image": "",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null,
  "OnBuild": null,
  "Labels": null
}
```

### Reproduction steps

1. Build image
2. Put the resource to Google Artifact Repository

```
  - name: backend-image
    type: docker-image
    icon: docker
    source:
      repository: ((gcp.region))-docker.pkg.dev/((gcp.project_id))/backend
      username: _json_key
      password: ((gcp.docker-registry.json_key))
<...>
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: backend
          outputs:
            - name: image
          params:
            CONTEXT: backend
          run:
            path: build
      - put: backend-image
        params:
          import_file: image/image.tar
```

### Expected behavior

The docker image should have Config entires as specified in the `Dockerfile`:
```
{
  "Hostname": "",
  "Domainname": "",
  "User": "node",
  "AttachStdin": false,
  "AttachStdout": false,
  "AttachStderr": false,
  "ExposedPorts": {
    "3000/tcp": {}
  },
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "NODE_VERSION=20.2.0",
    "YARN_VERSION=1.22.19",
    "NODE_ENV=production"
  ],
  "Cmd": [
    "/bin/sh",
    "-c",
    "npm run db:migrate && npm start"
  ],
  "ArgsEscaped": true,
  "Image": "",
  "Volumes": {
    "/var/resources": {}
  },
  "WorkingDir": "/app",
  "Entrypoint": [
    "docker-entrypoint.sh"
  ],
  "OnBuild": null,
  "Labels": null
}
```

### Additional context

The `Dockerfile`:
```
# Build stage
FROM node:20 AS dev

ENV NODE_ENV=dev

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --omit=dev

COPY . .
RUN npm run generate

RUN mkdir -p /var/resources && \
    chown node:node /var/resources && \
    chmod 757 /var/resources
VOLUME /var/resources

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]

# Production stage
FROM node:20-alpine3.16 AS production

ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm ci --only=production

COPY . .
RUN npm run generate

RUN mkdir -p /var/resources && \
    chown node:node /var/resources && \
    chmod 757 /var/resources
VOLUME /var/resources

USER node

EXPOSE 3000

CMD npm run db:migrate && npm start
```
