### ISSUE TITLE
option for loading build arg files from yaml, supporting dynamic multiline build args

### ISSUE THREAD

**Issue by featheredtoast** [concourse/oci-build-task#122]
### Is your feature request related to a problem? Please describe.

Current build arg file doesn't support multiline build args. However you're able to pass in multiline build args like:

```
params:
  BUILD_ARG_MULTILINE: |
    first line
    second line
    third line
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
```

I'd like to have a setup like the following

`myvars.yaml` - from an input, `my-input`
```
  BUILD_ARG_FOO: |
    first line
    second line
    third line
```

task definition:
```
- task my-oci-build-task
  params:
    BUILD_ARGS_FILE: my-input/myvars.yaml
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: concourse/oci-build-task
  inputs:
    - name: my-input
```

When the docker image is built, the build arg `FOO` has a value of:
```
first line
second line
third line
```

### Describe the solution you'd like

Rather than a `key=value` file, give an option to pass a yaml file for build args, in the same way we can for raw params direct in the build job.

### Describe alternatives you've considered

Currently I'm generating and outputting the entire task from the source, and then feeding that (as a var) into a task defined with a `file` param.

This works but is not ideal as the task definition moves to the program generating the build arg params.

I've also tried doing this with load_var steps, but build arg params here are also dynamic so I'm unable to pass them down from a load_var step.
