### ISSUE TITLE
Failed to build image in Concourse due to readonly fs

### ISSUE THREAD

**Issue by dmytro-zhernosiekov-rft** [concourse/oci-build-task#61]
Hi,
Updated Concourse to 6.7.5 version and enabled `containerd`. Just after that was not able to build image with `oci-build-task`.
Here is code:
```
jobs:
- name: build-docs
  plan:
  - get: docs-git
    trigger: true
  - task: build-docs-container
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      caches:
      - path: cache
      inputs:
      - name: docs-git
      outputs:
      - name: image
      params:
        CONTEXT: docs-git
      run:
        path: build
```
This code was ok on 6.7.2 concourse and after upgrade to 6.7.5 Concourse and enable `containerd` I got this error:
```
#10 0.077 container_linux.go:367: starting container process caused: process_linux.go:340: applying cgroup configuration for process caused: mkdir /sys/fs/cgroup/cpuset/buildkit: read-only file system
#10 ERROR: executor failed running [/bin/sh -c apk -q add gcc musl-dev]: exit code: 1
```
It just try to install some packages in alpine image. 
I found that this topic was discussed in concourse github issue and it looked like `/dev/shm` size. I checked our Concourse worker setup and there are already 64Mb assigned to shared memory. 

Could you looks at this issue?

What I found:
https://github.com/concourse/concourse/pull/6348
https://github.com/vito/oci-build-task/issues/38
