### ISSUE TITLE
Task does not resolve BUILD_ARG_* params correctly

### ISSUE THREAD

**Issue by kardashov** [concourse/oci-build-task#67]
How to reproduce:

- Take this Dockerfile https://github.com/concourse/oci-build-task/blob/master/testdata/build-args/Dockerfile
- configure task with following params:
```yml
params:
  BUILD_ARG_some_arg: some_value  
  BUILD_ARG_some_other_arg: some_other_value
```

Build fails with error:
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c test "$some_arg" = "some_value "]: exit code: 1
