### ISSUE TITLE
How to migrate load_base from docker-image

### ISSUE THREAD

**Issue by guillaumBrisard** [concourse/oci-build-task#69]
Hi, 

How to migrate **load_base** please:
```yaml
resources:
- name: openjdk-11
  type: docker-image
  source:
    repository: ((our.repo))/adoptopenjdk/openjdk11
    tag: alpine-jre
    <<: *repo-conf

jobs:
- name: job01
  plan:
  [...]
  - get: openjdk-11
    params: { save: true }
  - put: docker-app
    params:
      load_base: openjdk-11
      build: output-build
      tag_file: version-app/version
  ```
    
I suppose something like that
```yaml
jobs:
- name: job01
  plan:
  [...]
  - get: openjdk-11
    params: { format: oci }
  - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        caches:
          - path: cache ????
        params:
          IMAGE_ARG_????: ????/image.tar
        inputs:
        - name: output-build
          path: .
        outputs:
        - name: image
        run:
          path: build
  - put: docker-app
    params: 
      image: image/image.tar
      version: version-app/version
```
    
But I don't know how to use **cache** properly
or how to set **IMAGE_ARG_*****

In the doc:
`For example, IMAGE_ARG_base_image=ubuntu/image.tar will set base_image to a local image reference for using ubuntu/image.tar`
I suppose, I had to replace **ubuntu** by **openjdk-11** with my example, but not sure
And I don't know, what to do with **base_image**:

Is it possible to have a doc for this use case please

Thx
