### ISSUE TITLE
Possibility to pass BUILD_ARG_* from inputs?

### ISSUE THREAD

**Issue by samed** [concourse/oci-build-task#75]
Hello,

Currently, I'm using BUILD_ARGS_FILE and populating args within another task and passing the output file to the oci-build-task as input. I'm just curious if there's the possibility to pass BUILD_ARG_* from inputs directly (eg. `BUILD_ARG_APP_VERSION: git-repo/.git/short_ref` )

**Comment by suhlig** [comment]
I am using [`load_var`](https://concourse-ci.org/load-var-step.html) for this purpose. 

See this [example](https://github.com/suhlig/concourse-task-library/blob/main/pipelines/ginkgo.yml) from my task library:

```yaml
- load_var: ginkgo-version
  file: ginkgo-release/version
- task: build-image
  file: lib/tasks/oci/build-image.yml
  params:
    BUILD_ARG_VERSION: v((.:ginkgo-version))
```

* `ginkgo-release` is a [`github-release` resource](https://github.com/concourse/github-release-resource), tracking [onsi/ginkgo](https://github.com/onsi/ginkgo). It writes the fetched release version to `ginkgo-release/version`
* This file is then loaded as variable `ginkgo-version` and used in the `BUILD_ARG_VERSION` parameter (with an additional `v`).
* Finally, the [Dockerfile](https://github.com/suhlig/concourse-task-library/blob/main/images/ginkgo/Dockerfile) uses the build arg `VERSION` to determine which version of `ginkgo` to install.

Hope this helps.
