### ISSUE TITLE
Building using an image from a private repository results in "x509: certificate signed by unknown authority".

### ISSUE THREAD

**Issue by chriseaton** [concourse/oci-build-task#83]
When our docker file specifies an image in a private repo, it causes the oci-build-task to fail. As far I could tell there's no way to specify a custom CA. 

```
ERROR: failed to do request: Head "https://our-private-repo/v2/shared/centos/manifests/latest": x509: certificate signed by unknown authority
```

**Comment by CJLove** [comment]
Here's a possible workaround, with the downside that you're basically forking the official `oci-build-task` image and using it in the interim:

1. Build your own `oci-build-task` image with a Dockerfile like this to add your `ca.crt` file to the image, and push to your private registry
```
FROM docker.io/concourse/oci-build-task:latest

COPY ca.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates
```
2. In your pipeline specify your `oci-build-task` image in place of the official one
```
...
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: fir.love.io:3005/amd64/oci-build-task
          # repository: concourse/oci-build-task
          tag: latest
...
```

**Comment by lrstanley** [comment]
related, that has a bit cleaner temporary solution that doesn't require making a custom image: https://github.com/concourse/oci-build-task/issues/70

Looking at the code, however, I believe adding an input for custom certs/ca should be pretty easy.

**Comment by PavGregor** [comment]
We were using the wraparound script approach from https://github.com/concourse/oci-build-task/issues/70#issuecomment-933674965 to import custom CAs during the build process, but from `oci-build-task:0.12.0` onwards that no longer works:
```
cp: can't create '/usr/local/share/ca-certificates/internal_ca.crt': No such file or directory
update-ca-certificates: not found
```

Is there still no officially supported way of passing custom CAs to `oci-build-task`? Does anyone have a working solution?

**Comment by taylorsilva** [comment]
My bad, I broke that for you. I've added the ca-certificates back into the image (lost it when I updated the Dockerfile to use wolfi as the base image).

I'm bumping other deps and then I'll push a new version out that should continue to allow this workaround to work.

Another thing you should be able to do now is directly configure buildkit to use your custom CA with the `BUILDKIT_EXTRA_CONFIG` param now. You'd set that param to something like:

```toml
[registry."my-registry.com"]
  ca=["/var/certs/my-ca.pem"]
```

And then in your task config, assuming one of your inputs contains the CA cert:

```yaml
platform: linux

inputs:
- name: certs
  path: /var/certs

#...rest of the task config
```

The absolute path only works if you're on >=7.5.0 of Concourse.

Actually, given this workaround, I'm going to consider this issue closed. The point of exposing the buildkit config was so we didn't have to keep adding params to this task. I'll try documenting this in the README for folks to find.
