### ISSUE TITLE
[Feature Request] Allow Dockerfile literal in task cfg

### ISSUE THREAD

**Issue by eckdanny** [concourse/oci-build-task#86]
For simple uses cases like: 

```yml
- task: build-image
   ...
      inputs:
      - name: my-build-output-from-another-task
        path: .
      params:
      - DOCKERFILE: |
         FROM nginx
         COPY . /usr/share/nginx/html
```

this is attractive for the same reasons as [_Dockerfile [with/without] context from stdin_](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin "Docker Docs").

**Comment by eckdanny** [comment]
What is the best workaround in the meantime?

[Guessing]: put _another_ task before the <samp>oci-build-task</samp> to write a 2-line <samp>Dockerfile</samp> to <samp>outputs</samp>, and then add to <samp>inputs</samp>?

**Comment by natto1784** [comment]
> What is the best workaround in the meantime?
I do this for a project of mine
```yml
  - task: push-image
    ...
      inputs:
      - name: bin
      run:
        path: sh
        args:
        - -c
        - |
          cat <<EOF > Dockerfile
          FROM arm64v8/ubuntu
          COPY bin/singh3 /usr/bin/singh3
          CMD ["singh3"]
          EOF
          build
```

**Comment by taylorsilva** [comment]
Use the built-in [mock resource](https://github.com/concourse/mock-resource/) to create files for you.

```yaml
resources:
- name: file
  type: mock
  source:
    create_files:
      Dockerfile: |
        FROM nginx
        COPY . /usr/share/nginx/html

jobs:
- name: build
  plan:
  - get: file
  - task: build
    ...
    config:
      inputs:
        - name: file
      run:
        path: build
      params:
        CONTEXT: file
```

Closing as not planned.
