### ISSUE TITLE
Using LABEL_

### ISSUE THREAD

**Issue by gabs77** [concourse/oci-build-task#95]
Can you give an example for using LABEL_ parameters ?

I do this : 
```yaml
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          params:
            CONTEXT: repo
            DOCKERFILE: repo/Dockerfile
            LABEL_Test: "it a test
          inputs:
            - name: repo
            - name: base-image
              optional: true
          outputs:
            - name: image
          run:
            path: build
```
The Dockerfile contains just : 
```
FROM  alpine:3.14
```

After the build, i execute the following command : 
`docker inspect [mybuild] `
 
 I can't see any label
